# .github/workflows/jekyll.yml
name: Run Jekyll on Push

on:
  push:
    # Optional: limit to specific branches or paths
    # branches: [main]
    # paths: [Gemfile, _config.yml, ...]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # or your preferred version

      - name: Install dependencies
        run: bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build
        # Or another Jekyll command you want to run
